# Setup
title:        Sudheera Njs
tagline:      Product Management . Web Development . StartUp . SEO and Marketing
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Sudheera Njs
  url:        http://sudhi.in/ 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown